onlyBuiltDependencies:
  - '@mercuryworkshop/scramjet'
  - '@petezah-games/scramjet'
  - bcrypt
  - better-sqlite3
  - bufferutil
  - esbuild
  - puppeteer
  - sharp

overrides:
  '@petezah-games/scramjet-controller': link:../.local/share/pnpm/global/5/node_modules/@petezah-games/scramjet-controller
